language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t anjuboura/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true anjuboura/react-test npm test -- --coverage

after_success:
 - docker build -t anjuboura/multi-client ./client 
 - docker build -t anjuboura/multi-server ./server
 - docker build -t anjuborua/multi-worker ./worker
 - docker build -t anjuborua/multi-nginx  ./nginx
   
 # Login to docker cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # Take those image and pushed it into docker hub
 
 - docker push anjuboura/multi-client 
 - docker push anjuboura/multi-server 
 - docker push anjuborua/multi-worker 
 - docker push anjuborua/multi-nginx  

